# Generated by Django 4.2.7 on 2026-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, help_text='For students, enter their roll number to link results', max_length=50, null=True),
        ),
    ]
