# Generated by Django 4.2.7 on 2026-02-02 15:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('description', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('4'))])),
            ],
            options={
                'verbose_name': 'Grading Rule',
                'verbose_name_plural': 'Grading Rules',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ProbabilisticGradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_marks_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Confidence threshold for full marks (default: 0.70)', max_digits=3)),
                ('partial_marks_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Confidence threshold for partial marks (default: 0.40)', max_digits=3)),
                ('partial_marks_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Percentage of marks to award for partial match (default: 70%)', max_digits=3)),
                ('use_keyword_matching', models.BooleanField(default=True)),
                ('use_similarity_scoring', models.BooleanField(default=True)),
                ('use_bayesian_inference', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Probabilistic Grading Config',
                'verbose_name_plural': 'Probabilistic Grading Configs',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('grade', models.CharField(max_length=5)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('4'))])),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.subject')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
